@Library('library')_
pipeline
{
    agent any
    stages
    {
       stage('ContDownload_Master')
        {
            steps
            {
                script
                {
                    cicd.newGit("maven")
                }
            }
            
        }
        stage('ContBuild_Master')
        {
            steps
            {
                script
                {
                    cicd.newMaven()
                }
            }
        }
        stage('ContDeployment_Master')
        {
            steps
            {
                script
                {
                    cicd.newDeploy("SharedLibrary1","172.31.0.175","testapp")
                }
            }
        }
        stage('ContTesting_Master')
        {
            steps
            {
                script
                {
                   cicd.newGit("FunctionalTesting")
                   cicd.runSelenium("SharedLibrary1")
                }
                
            }
        }
        
    }
}
